version: "3.7"
services:
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./data:/mysql_data/mysql
    ports:
      - "3306:3306"
  app: &app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
      args:
        RUBY_VERSION: '2.6.5'
        NODE_MAJOR: '12'
        BUNDLER_VERSION: '2.0.2'
  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    volumes:
      - .:/nakigara
    depends_on:
      - db
      - redis
  rails:
    <<: *backend
    command: >
      rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  nginx:
    image: "nginx:1.17.6-alpine"
    command: nginx -g "daemon off;"
    volumes:
      - ./public:/var/www/nakigara/public
    container_name: nakigara-nginx
    depends_on:
      - app
    ports:
      - "80:80"
  redis:
    image: "redis:5.0.7-alpine"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
    container_name: nakigara-redis
